[package]
name = "expanded-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-types.workspace = true
starknet.workspace = true
anyhow = "1.0"
