[package]
name = "cairo-type-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-types.workspace = true

proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

serde.workspace = true

starknet.workspace = true

[features]
default = ["std"]
std = []
